export const Images = {
    logo: require('./logo_a2c.png'),
    logo_get_location: require('./logo_get_location.png'),
    pin_mapa: require('./pin_mapa.png'),
    doctor: require('./doctor.png'),
    logoA2C: require('./logoA2C.png'),
    clipboard: require('./clipboard.png'),
    thumbUp: require('./thumbUp.png'),
    logo_blue: require('./logo_blue.png'),
    logofb: require('./logofb.png'),
    logogoogle: require('./logogoogle.png'),
    ciclo_menstrual: require('./ciclo_menstrual.png'),
    estres: require('./estres.png'),
    oxigen_blood: require('./oxigen_blood.png'),
    presion_arterial: require('./presion_arterial.png'),
    temper: require('./temper.png'),
    presion_sanguinea: require('./presion_sanguinea.png'),
    ritmo_cardiaco: require('./ritmo_cardiaco.png'),
    sensor_cardiaco: require('./sensor_cardiaco.png'),
    sueño: require('./sueño.png'),

};